language: swift
osx_image: xcode9.2


before_install:
 - gem install cocoapods
script:
 - pod repo update && pod update
 - set -o pipefail
 - xcodebuild -workspace Example/RxFirebase.xcworkspace -scheme RxFirebase -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - pod lib lint RxFirebase.podspec --verbose
