language: swift
osx_image: xcode9.2


before_install:
 - gem install cocoapods
 - brew update
script:
 - set -o pipefail
 - xcodebuild -workspace Example/RxFirebase.xcworkspace -scheme RxFirebase -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 - pod lib lint RxFirebase.podspec
